### ISSUE TITLE
[OGRE-480] Branch 1.9 does not build on Yosemite

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#138]
<b>[reporter="JulienF", created="Mon, 23 Mar 2015 10:59:18 +0100"]</b>
<p>Since commit c1ea4a0f15f5 on branch v1-9, Ogre does not build on Mac OS X 10.10</p>

<p>I have the following error upon linking:</p>

<p>Linking CXX shared library ../lib/macosx/Ogre.framework/Ogre<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimable.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimable.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimable.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimation.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimation.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimation.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationState.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationState.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationState.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationTrack.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationTrack.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAnimationTrack.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchive.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchive.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchive.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchiveManager.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchiveManager.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreArchiveManager.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAtomicScalar.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAtomicScalar.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAtomicScalar.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAutoParamDataSource.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAutoParamDataSource.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAutoParamDataSource.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAxisAlignedBox.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAxisAlignedBox.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreAxisAlignedBox.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboard.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboard.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboard.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboardChain.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIdE16getAdjustedInputEd in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboardChain.cpp.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OgreBillboardChain.cpp.o<br/>
duplicate symbol __ZN4Ogre18ControllerFunctionIfE16getAdjustedInputEf in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedA<br/>
...<br/>
    CMakeFiles/OgreMain.dir/src/OSX/OgreConfigDialog.mm.o<br/>
duplicate symbol _<em>ZN4Ogre18ControllerFunctionINS_7Vector3EE16getAdjustedInputES1</em> in:<br/>
    CMakeFiles/OgreMain.dir/src/OgreAlignedAllocator.cpp.o<br/>
    CMakeFiles/OgreMain.dir/src/OSX/OgreConfigDialog.mm.o<br/>
ld: 561 duplicate symbols for architecture x86_64<br/>
clang: error: linker command failed with exit code 1 (use -v to see invocation)<br/>
make<span class="error">&#91;2&#93;</span>: *** <span class="error">&#91;lib/macosx/Ogre.framework/Versions/1.9.0/Ogre&#93;</span> Error 1<br/>
make<span class="error">&#91;1&#93;</span>: *** <span class="error">&#91;OgreMain/CMakeFiles/OgreMain.dir/all&#93;</span> Error 2<br/>
make: *** <span class="error">&#91;all&#93;</span> Error 2<br/>
<span class="error">&#91;hg on v1-9:&#93;</span></p>

**Comment by paroj** [comment]
<b><i>[author="julienf", created="Mon, 23 Mar 2015 11:03:21 +0100"]</i></b>
<p>I am not the only one to have spotted the issue:</p>

<p><a href="http://stackoverflow.com/questions/29043627/ogre1-9-build-error-on-osx" class="external-link" rel="nofollow">http://stackoverflow.com/questions/29043627/ogre1-9-build-error-on-osx</a></p>

**Comment by paroj** [comment]
<b><i>[author="flavio", created="Wed, 23 Sep 2015 16:58:47 +0200"]</i></b>
<p>We managed to build it on  Mac OS X 10.10 with some modifications, would that help Ogre devs if we propose a pull request (from default branch) ? However theses modifications will break compatibility with OsX 10.7 (which was the previous target).</p>

**Comment by paroj** [comment]
<b><i>[author="flavio", created="Thu, 24 Sep 2015 09:36:11 +0200"]</i></b>
<p>I've just submitted a pull request : </p>

<p><a href="https://bitbucket.org/sinbad/ogre/pull-requests/569/fixes-to-build-ogre-on-macosx/diff" class="external-link" rel="nofollow">https://bitbucket.org/sinbad/ogre/pull-requests/569/fixes-to-build-ogre-on-macosx/diff</a></p>
