### ISSUE TITLE
Error to build android

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#1603]
version 1.12.7
a01b61b027c7e8b79ff928b5d64607815401acdc

cmake -DCMAKE_TOOLCHAIN_FILE=path/to/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_NDK=path/to/android-ndk .

[ 40%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/Threading/OgreDefaultWorkQueueStandard.cpp.o
[ 40%] Linking CXX static library ../lib/libOgreMainStatic.a
Error running link command: No such file or directory
make[2]: *** [OgreMain/CMakeFiles/OgreMain.dir/build.make:3250: lib/libOgreMainStatic.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:570: OgreMain/CMakeFiles/OgreMain.dir/all] Error 2
make: *** [Makefile:172: all] Error 2

**Comment by Joilnen** [comment]
git 8ff1a4046716244fc4b3a3e44e5b6abeda755b0a

trying these lines I got this

cmake -P ci-build.cmake
...
[ 36%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/OgreSearchOps.cpp.o
[ 37%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/Android/OgreAPKZipArchive.cpp.o
[ 37%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/Threading/OgreDefaultWorkQueueStandard.cpp.o
[ 37%] Linking CXX static library ../lib/libOgreMainStatic.a
Error running link command: No such file or directory
make[2]: *** [OgreMain/CMakeFiles/OgreMain.dir/build.make:3250: lib/libOgreMainStatic.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:1434: OgreMain/CMakeFiles/OgreMain.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**Comment by paroj** [comment]
the actual error must have happened earlier. please post the full log.

**Comment by Joilnen** [comment]
It seems something related with imgui

/home/joilnen/ogre3d_devel/ogre/Components/Overlay/src/imgui/misc/freetype/imgui_freetype.cpp: In function ‘bool ImFontAtlasBuildWithFre↳ eType(FT_Library, ImFontAtlas*, unsigned int)’:                                                                                       
/home/joilnen/ogre3d_devel/ogre/Components/Overlay/src/imgui/misc/freetype/imgui_freetype.cpp:334:72: error: ‘void* memset(void*, int, s↳ ize_t)’ clearing an object of type ‘struct ImFontBuildSrcDataFT’ with no trivial copy-assignment; use assignment or value-initializati↳ on instead [-Werror=class-memaccess]
  334 |     memset(src_tmp_array.Data, 0, (size_t)src_tmp_array.size_in_bytes());    
      |                                                                        ^    
/home/joilnen/ogre3d_devel/ogre/Components/Overlay/src/imgui/misc/freetype/imgui_freetype.cpp:295:8: note: ‘struct ImFontBuildSrcDataFT’↳  declared here
  295 | struct ImFontBuildSrcDataFT    
      |        ^~~~~~~~~~~~~~~~~~~~    
/home/joilnen/ogre3d_devel/ogre/Components/Overlay/src/imgui/misc/freetype/imgui_freetype.cpp:335:72: error: ‘void* memset(void*, int, s↳ ize_t)’ clearing an object of type ‘struct ImFontBuildDstDataFT’ with no trivial copy-assignment; use assignment or value-initializati↳ on instead [-Werror=class-memaccess]
  335 |     memset(dst_tmp_array.Data, 0, (size_t)dst_tmp_array.size_in_bytes());    
      |                                                                        ^    
/home/joilnen/ogre3d_devel/ogre/Components/Overlay/src/imgui/misc/freetype/imgui_freetype.cpp:308:8: note: ‘struct ImFontBuildDstDataFT’↳  declared here
  308 | struct ImFontBuildDstDataFT    
      |        ^~~~~~~~~~~~~~~~~~~~    
cc1plus: all warnings being treated as errors    
make[2]: *** [Components/Overlay/CMakeFiles/OgreOverlay.dir/build.make:343: Components/Overlay/CMakeFiles/OgreOverlay.dir/src/imgui/misc↳ /freetype/imgui_freetype.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2377: Components/Overlay/CMakeFiles/OgreOverlay.dir/all] Error 2    
make[1]: *** Waiting for unfinished jobs....    
make: *** [Makefile:183: all] Error 2

**Comment by paroj** [comment]
remove this line
https://github.com/OGRECave/ogre/blob/d381eb2683b06c0b64ff38050f6fda47e72c680e/ci-build.cmake#L2

**Comment by Joilnen** [comment]
yes but I could to build it before lasts commits I mean it works fine in 1.12.6

**Comment by paroj** [comment]
then you likely had imgui disabled, as these warnings have been there also with 1.12.6

**Comment by Joilnen** [comment]
Now it is compiling and working fine, but shouldn't a good idea, include imgui as submodule, or at least as reference to a specific git version of that ?

**Comment by paroj** [comment]
the problem is actually that it is included as a submodule:
https://github.com/OGRECave/ogre/issues/1332#issuecomment-563189058

given the amount of problems it produces, I consider rather using cmake to download it - similar to the other dependencies

**Comment by Joilnen** [comment]
Maybe you could just set .gitsubmodule proprieties of imgui sub in the project, to update only some specific source code, no ?
