### ISSUE TITLE
RTSS errors with the 13.6 versions

### ISSUE THREAD

**Issue by eventhorizon5** [OGRECave/ogre#2786]
#### System Information
- Ogre Version: 13.6.2
- Operating System / Platform: Debian Linux 12 (Testing)
- RenderSystem: OpenGL3Plus

#### Detailled description
When using the RTSS system (for custom procedural geometry) and the OpenGL3Plus renderer, I'm getting shader compiler errors when using the setEnvironmentMap function for alpha blending.  My code works fine with Ogre 13.5.3, but something changed in 13.6, breaking it for me.  Do you know if anyone else is having issues like this?  I'm not sure if it's a bug, or something I'm doing wrong in my code.

#### Ogre.log
```
21:03:50: Running simulation... 
21:03:50: Program '99f2d70079862523dbd1d326bbafb7f5_VS' is not supported: '99f2d70079862523dbd1d326bbafb7f5_VS' 0(41) : error C7011: implicit cast from "mat3" to "mat4"
0(41) : error C1102: incompatible type for parameter #3 ("mWorldIT.49")
0(41) : error C1102: incompatible type for parameter #4 ("vPos.50")
0(41) : error C1102: incompatible type for parameter #5 ("vNormal.51")
0(41) : error C1103: too few parameters in function call
21:03:50: Error: RTSS: failed to create GpuPrograms for Pass 0 of '0:MainWindows'
21:03:50: Error in render operation
```

These errors happen when using setEnvironmentMap:
```
Ogre::MaterialPtr mMat = CreateMaterial(matname, "General");
Ogre::TextureUnitState* state = mMat->getTechnique(0)->getPass(0)->createTextureUnitState(texturename); 
Ogre::TextureUnitState* spec_state = mMat->getTechnique(0)->getPass(0)->createTextureUnitState(specular_texturename);
Ogre::TextureUnitState* blend_state = mMat->getTechnique(0)->getPass(0)->createTextureUnitState(blend_texturename);

if (spec_state)
	spec_state->setColourOperation(Ogre::LBO_ALPHA_BLEND);

if (blend_state)
{
	blend_state->setColourOperationEx(Ogre::LBX_BLEND_CURRENT_ALPHA);
	if (spherical == true)
		blend_state->setEnvironmentMap(true, Ogre::TextureUnitState::ENV_CURVED);
	else
		blend_state->setEnvironmentMap(true, Ogre::TextureUnitState::ENV_PLANAR);
}
```

**Comment by paroj** [comment]
can you call `ApplicationContextBase::setRTSSWriteShadersToDisk` and attach `99f2d70079862523dbd1d326bbafb7f5_VS.glsl`?

Also attach the textures you are using. It sounds like a texture type mismatch. ENV_CURVED requires a 3D texture, while ENV_PLANAR requires  2D texture

**Comment by eventhorizon5** [comment]
I set the code up to only use Ogre::TextureUnitState::ENV_PLANAR.  I tried using ENV_NORMAL which works, but that requires a cubic texture.  I'm actually getting a different error this time, I'm going through the code to figure out why.

````
14:02:20: Program '289c33c0632f8a5496ff7fd9f983b6b5_VS' is not supported: '289c33c0632f8a5496ff7fd9f983b6b5_VS' 0:34(2): error: no matching function for call to `FFP_GenerateTexCoord_EnvMap_Sphere(mat4, mat3, vec4, vec3, vec2)'; candidates are:
0:34(2): error:    void FFP_GenerateTexCoord_EnvMap_Sphere(mat4, mat4, mat4, vec4, vec3, vec2)
14:02:20: RTSS: using 289c33c0632f8a5496ff7fd9f983b6b5_VS for Pass 0 of '0:MainWindows2'
14:02:20: RTSS: using 5b7b8bcddeec059ce16fe586c0bdb207_FS for Pass 0 of '0:MainWindows2'
14:02:20: Error: RTSS: failed to create GpuPrograms for Pass 0 of '0:MainWindows2'
````

[289c33c0632f8a5496ff7fd9f983b6b5_VS.txt](https://github.com/OGRECave/ogre/files/10747115/289c33c0632f8a5496ff7fd9f983b6b5_VS.txt)

**Comment by paroj** [comment]
looks like you did not update `Media/RTShaderLib` when updating to 13.6

**Comment by eventhorizon5** [comment]
Thanks, that fixed it.  I didn't think I needed to update the Media files between minor releases, I did it when going from 12 to 13.
