### ISSUE TITLE
Compiling ogre latest version iOS

### ISSUE THREAD

**Issue by AndreAhmed** [OGRECave/ogre#691]
Hi,
I tried to compile the latest github version, but I'm getting that compilation error when I run my own ogre sample

Unknown type name 'PFNGLACTIVESHADERPROGRAMEXTPROC'

I include #include <EAGL/OgreEAGL2Window.h>

**Comment by AndreAhmed** [comment]
Where is GLES2Context.h ? What should I use for a replacement ? I was using 1.90 in my code chain, now I want to upgrade to 1.11

**Comment by AndreAhmed** [comment]
#if !defined(WIN32) && !defined(WIN32UWP)
#include <OgreGLES2Context.h>
#include <EAGL/OgreEAGLES2Context.h>
#include <EAGL/OgreEAGL2Window.h>
#endif

**Comment by paroj** [comment]
it moved to glsupport. Also using the rendersystem internals is bad practice.
