### PR TITLE
Update SDL2 and Assimp to fix compiler erros with newest MinGW-w64

### PR DESCRIPTION
**Pull request by markellus**
The currently used versions of SDL2 and Assimp do not compile with the newest version of MinGW-w64 (GCC 12.2+) from MSYS2. The issues where fixed in SDL2 2.24.1 and Assimp 5.2.5.

SDL2 issue:
https://github.com/libsdl-org/SDL/issues/5728
https://github.com/libsdl-org/SDL/commit/d2c4d74dd0302369251dce9375b49f394e54f76a

I can't find a ticket for Assimp but i get a lot of these errors, which disappear after updating to 5.2.5:
`ingw64/include/c++/12.2.0/bits/new_allocator.h:175:11: error: array subscript 'const aiVector3t<float>[1]' is partly outside array bounds of 'std::__cxx11::list<aiVector3t<float> > [1]' [-Werror=array-bounds]
  175 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }`

### CODE REVIEW

**Comment by paroj** [comment]
:+1: thanks
